ARG BASE_IMAGE
FROM ${BASE_IMAGE}

USER root

ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk \
    PATH=/usr/lib/jvm/java-21-openjdk/bin:${PATH} \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN apk add --no-cache \
      bash \
      coreutils \
      docker-cli \
      git \
      jq \
      maven \
      openjdk21-jdk \
      openssl \
      python3 \
    && test -x "${JAVA_HOME}/bin/javac" \
    && javac -version \
    && mvn -version

ENTRYPOINT ["/bin/bash"]
