/* Native journey evidence is read-only; declaration and business decisions use signed CLI actions. */
(() => {
  const node = (tag, text, cls) => { const e = document.createElement(tag); if (text !== undefined) e.textContent = text; if (cls) e.className = cls; return e; };
  function requests(host, payload) {
    document.getElementById('decision-count').textContent = String((payload.requests || []).filter(r => r.status === 'awaiting-human').length);
    host.append(node('h2', 'Decisions for this run'));
    if (!payload.requests?.length) host.append(node('p', 'No decision requests have been recorded for this run.'));
    for (const request of payload.requests || []) {
      const card = node('section', undefined, 'run-card');
      card.append(node('h3', request.action_kind), node('p', request.reason), node('p', `Owner: ${request.owner_role} · ${request.status}`));
      card.append(node('p', `Request ${request.id} · affected cases: ${request.affected_cases.join(', ')}`));
      if (request.decision) card.append(node('p', `Recorded by ${request.decision.actor}: ${request.decision.outcome}`));
      else card.append(node('p', 'Use the signed journey CLI to record this decision. Replaying does not accept the timestamp loss or promote equivalence.'));
      host.append(card);
    }
  }
  function render(host, payload) {
    host.replaceChildren();
    if (payload.status === 'invalid' || payload.signature_verified !== true) throw new Error('The native journey signature could not be verified.');
    host.append(node('p', `iDempiere · ${payload.run_id}`, 'run-eyebrow'), node('h1', payload.mode === 'extend' ? 'Generated native journey' : 'Native journey replay'), node('p', payload.status, 'run-note'));
    host.append(node('p', payload.mode === 'extend' ? `Local Oracle and PostgreSQL · agent-generated partial-invoicing harness · ${payload.model_calls} recorded builder invocation(s). Native verdicts are deterministic. Local signatures are not independent attestation.` : 'Local Oracle and PostgreSQL · unchanged MS86 harnesses · builder idle · zero model calls. Local signatures are not independent attestation.', 'run-note'));
    const latestStage = payload.events.filter(e => e.type === 'stage').at(-1);
    if (!payload.receipt && latestStage) host.append(node('p', `Current stage: ${latestStage.payload.stage}`, 'run-note'));
    const receipt = payload.receipt;
    if (receipt) {
      const figures = node('div', undefined, 'run-figures');
      const outcomes = payload.mode === 'extend'
        ? [['Bounded partial invoicing equivalent', receipt.bounded_partial_invoicing_equivalence], ['Harness generated by agent', receipt.agent_generated], ['Unattended extension', receipt.unattended_extension]]
        : [['Known findings reproduced', receipt.known_findings_reproduced], ['Bounded operations equivalent', receipt.bounded_operations_equivalence], ['Unattended replay', receipt.unattended_run]];
      outcomes.push(['Human interventions outside designed stops', receipt.human_interventions_outside_designed_stops]);
      for (const [label, value] of outcomes) {
        const item = node('section', undefined, 'run-card'); item.append(node('h2', label), node('p', String(value))); figures.append(item);
      }
      host.append(figures);
    }
    const cleanup = payload.events.filter(e => e.type === 'cleanup').at(-1);
    host.append(node('p', cleanup ? `Cleanup recorded: ${cleanup.payload.complete ? 'complete' : 'incomplete'}. Credentials destroyed: ${cleanup.payload.credentials_destroyed}.` : 'Cleanup has not yet been recorded; the run may still own local containers.', 'run-note'));
    requests(host, payload);
    const timeline = node('ol', undefined, 'run-steps');
    for (const event of payload.events) {
      const p = event.payload;
      const step = node('li', undefined, 'run-step');
      step.append(node('h3', `${event.type} · ${event.at}`), node('p', p.stage || p.command || p.reason || [p.case, p.lane, p.classification].filter(Boolean).join(' · ')));
      if (p.exit_code !== undefined) step.append(node('p', `Process exit ${p.exit_code}`));
      if (p.diagnostic) { const details = node('details'); details.append(node('summary', 'Recorded diagnostic'), node('pre', p.diagnostic)); step.append(details); }
      timeline.append(step);
    }
    host.append(node('h2', 'Verified journal events'), timeline, node('p', `Journal head: ${payload.journal_head_sha256}`, 'run-note'));
    host.append(node('p', 'No claim of full application, schema or platform equivalence. The fractional timestamp finding remains open.', 'run-note'));
  }
  let sequence = 0;
  async function refreshQueue() {
    const host = document.getElementById('journey-decisions');
    const current = ++sequence;
    host.hidden = window.LightyearContext.state.estate !== 'idempiere';
    if (host.hidden) return;
    try {
      const response = await fetch(`/api/workflow/execution?${window.LightyearContext.query()}`, {cache:'no-store'});
      if (!response.ok) throw new Error('Journey service unavailable');
      const payload = await response.json();
      if (current !== sequence) return;
      host.replaceChildren();
      if (payload.status === 'unavailable') { host.append(node('p', payload.reason)); return; }
      if (payload.signature_verified !== true) throw new Error('Journey signature could not be verified');
      host.append(node('p', `${payload.run_id} · ${payload.status}`)); requests(host, payload);
    } catch (e) { if (current === sequence) host.replaceChildren(node('p', e.message)); }
  }
  document.addEventListener('tower-context-change', refreshQueue);
  setInterval(() => { if (window.LightyearContext.state.estate === 'idempiere' && !document.getElementById('decision-workspace').hidden) refreshQueue(); }, 5000);
  window.LightyearJourneys = {render};
})();
