-- Synthetic catalog case ORA-TYPE-016-CASE-01; source Oracle 26ai.
DECLARE
  v_canonical VARCHAR2(128);
  v_null_value VARCHAR2(128);
  v_boundary VARCHAR2(128);
  v_recovery VARCHAR2(128);
  v_time_value VARCHAR2(128);
  v_format_a VARCHAR2(128);
  v_format_b VARCHAR2(128);
  v_sink VARCHAR2(128);
  v_length NUMBER; v_comparison NUMBER; v_overflow_code NUMBER := 0; v_json VARCHAR2(4000);
BEGIN
  EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_COMP=BINARY';
  EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_SORT=BINARY';
  SELECT CAST('A' AS CHAR(3)), CAST(NULL AS CHAR(3 CHAR)), LENGTH(CAST('A' AS CHAR(3))),
         CASE WHEN CAST('A' AS CHAR(3)) = CAST('A  ' AS CHAR(3)) THEN 1 ELSE 0 END
    INTO v_canonical, v_null_value, v_length, v_comparison FROM dual;
  EXECUTE IMMEDIATE 'CREATE TABLE LY_ORA_TYPE_016_CASE_01 (v CHAR(3 CHAR))';
  BEGIN
    EXECUTE IMMEDIATE 'INSERT INTO LY_ORA_TYPE_016_CASE_01 VALUES (:1)' USING 'ABC';
    EXECUTE IMMEDIATE 'SELECT v FROM LY_ORA_TYPE_016_CASE_01' INTO v_boundary;
    BEGIN
      EXECUTE IMMEDIATE 'INSERT INTO LY_ORA_TYPE_016_CASE_01 VALUES (:1)' USING 'ABCD';
    EXCEPTION WHEN OTHERS THEN v_overflow_code := SQLCODE;
    END;
    SELECT CAST('A' AS CHAR(3)) INTO v_recovery FROM dual;
  EXCEPTION WHEN OTHERS THEN
    EXECUTE IMMEDIATE 'DROP TABLE LY_ORA_TYPE_016_CASE_01 PURGE'; RAISE;
  END;
  EXECUTE IMMEDIATE 'DROP TABLE LY_ORA_TYPE_016_CASE_01 PURGE';
  SELECT JSON_OBJECT('case_id' VALUE 'ORA-TYPE-016-CASE-01', 'observations' VALUE
    JSON_OBJECT('canonical' VALUE v_canonical NULL ON NULL) RETURNING VARCHAR2(4000)) INTO v_json FROM dual;
  DBMS_OUTPUT.PUT_LINE('LY_TYPES_OBSERVATION=' || v_json);
END;
/
