-- Synthetic bounded catalog case ORA-TYPE-054-CASE-03; Oracle 26ai.
DECLARE
 v_canonical VARCHAR2(128);
 v_null_value VARCHAR2(128);
 v_boundary VARCHAR2(128);
 v_recovery VARCHAR2(128);
 v_session_value VARCHAR2(128);
 v_sink VARCHAR2(128);
 v_zoned TIMESTAMP WITH LOCAL TIME ZONE;
 v_length NUMBER; v_comparison NUMBER; v_overflow_code NUMBER := 0; v_json VARCHAR2(4000);
BEGIN
 EXECUTE IMMEDIATE 'ALTER SESSION SET TIME_ZONE = ''+00:00''';
 SELECT CAST(TO_TIMESTAMP_TZ('2026-09-01 17:30:00.123456 +05:30', 'YYYY-MM-DD HH24:MI:SS.FF6 TZH:TZM') AS TIMESTAMP WITH LOCAL TIME ZONE) INTO v_zoned FROM dual;
 SELECT TO_CHAR(SYS_EXTRACT_UTC(v_zoned), 'YYYY-MM-DD"T"HH24:MI:SS.FF6'), TO_CHAR(CAST(NULL AS TIMESTAMP), 'YYYY-MM-DD"T"HH24:MI:SS.FF6'),
 TO_CHAR(SYS_EXTRACT_UTC(TO_TIMESTAMP_TZ('2026-12-31 23:30:00 -01:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM')), 'YYYY-MM-DD"T"HH24:MI:SS.FF6'),
 CASE WHEN v_zoned = TO_TIMESTAMP_TZ('2026-09-01 12:00:00.123456 +00:00', 'YYYY-MM-DD HH24:MI:SS.FF6 TZH:TZM') THEN 1 ELSE 0 END
 INTO v_canonical, v_null_value, v_boundary, v_comparison FROM dual;
 BEGIN
 SELECT TO_CHAR(TO_TIMESTAMP_TZ('2026x09x01 12:00:00 +00:00', 'FXYYYY-MM-DD HH24:MI:SS TZH:TZM'), 'YYYY-MM-DD"T"HH24:MI:SS.FF6') INTO v_sink FROM dual;
 EXCEPTION WHEN OTHERS THEN v_overflow_code := SQLCODE;
 END;
 SELECT TO_CHAR(SYS_EXTRACT_UTC(v_zoned), 'YYYY-MM-DD"T"HH24:MI:SS.FF6') INTO v_recovery FROM dual;
 EXECUTE IMMEDIATE 'ALTER SESSION SET TIME_ZONE = ''+05:30''';
 SELECT TO_CHAR(v_zoned, 'YYYY-MM-DD"T"HH24:MI:SS.FF6') INTO v_session_value FROM dual;
 SELECT JSON_OBJECT('case_id' VALUE 'ORA-TYPE-054-CASE-03', 'observations' VALUE
 JSON_OBJECT('comparison' VALUE v_comparison, 'session_value' VALUE v_session_value NULL ON NULL) RETURNING VARCHAR2(4000)) INTO v_json FROM dual;
 DBMS_OUTPUT.PUT_LINE('LY_TYPES_OBSERVATION=' || v_json);
END;
/
