-- Synthetic bounded catalog case ORA-TYPE-029-CASE-04; Oracle 26ai.
DECLARE
 v_canonical VARCHAR2(128);
 v_null_value VARCHAR2(128);
 v_boundary VARCHAR2(128);
 v_recovery VARCHAR2(128);
 v_session_value VARCHAR2(128);
 v_sink VARCHAR2(128);
 v_zoned TIMESTAMP WITH TIME ZONE;
 v_length NUMBER; v_comparison NUMBER; v_overflow_code NUMBER := 0; v_json VARCHAR2(4000);
BEGIN
  EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_COMP=BINARY';
  EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_SORT=BINARY';
  SELECT CAST(UNISTR('\03A9') AS NCHAR(3)), CAST(NULL AS NCHAR(3)), LENGTH(CAST(UNISTR('\03A9') AS NCHAR(3))),
         CASE WHEN CAST(UNISTR('\03A9') AS NCHAR(3)) = CAST(UNISTR('\03A9  ') AS NCHAR(3)) THEN 1 ELSE 0 END
    INTO v_canonical, v_null_value, v_length, v_comparison FROM dual;
  EXECUTE IMMEDIATE 'CREATE TABLE LY_ORA_TYPE_029_CASE_04 (v NCHAR(3))';
  BEGIN
    EXECUTE IMMEDIATE 'INSERT INTO LY_ORA_TYPE_029_CASE_04 VALUES (:1)' USING UNISTR('\03A9\03A9\03A9');
    EXECUTE IMMEDIATE 'SELECT v FROM LY_ORA_TYPE_029_CASE_04' INTO v_boundary;
    BEGIN
      EXECUTE IMMEDIATE 'INSERT INTO LY_ORA_TYPE_029_CASE_04 VALUES (:1)' USING UNISTR('\03A9\03A9\03A9\03A9');
    EXCEPTION WHEN OTHERS THEN v_overflow_code := SQLCODE;
    END;
    SELECT CAST(UNISTR('\03A9') AS NCHAR(3)) INTO v_recovery FROM dual;
  EXCEPTION WHEN OTHERS THEN
    EXECUTE IMMEDIATE 'DROP TABLE LY_ORA_TYPE_029_CASE_04 PURGE'; RAISE;
  END;
  EXECUTE IMMEDIATE 'DROP TABLE LY_ORA_TYPE_029_CASE_04 PURGE';
  SELECT TO_CHAR(v_length, 'FM9990') INTO v_session_value FROM dual;
  SELECT RAWTOHEX(UTL_I18N.STRING_TO_RAW(v_canonical, 'AL32UTF8')) INTO v_canonical FROM dual;
  SELECT RAWTOHEX(UTL_I18N.STRING_TO_RAW(v_boundary, 'AL32UTF8')) INTO v_boundary FROM dual;
  SELECT RAWTOHEX(UTL_I18N.STRING_TO_RAW(v_recovery, 'AL32UTF8')) INTO v_recovery FROM dual;
 SELECT JSON_OBJECT('case_id' VALUE 'ORA-TYPE-029-CASE-04', 'observations' VALUE
 JSON_OBJECT('comparison' VALUE v_comparison, 'overflow_code' VALUE v_overflow_code, 'recovery' VALUE v_recovery, 'session_value' VALUE v_session_value NULL ON NULL) RETURNING VARCHAR2(4000)) INTO v_json FROM dual;
 DBMS_OUTPUT.PUT_LINE('LY_TYPES_OBSERVATION=' || v_json);
END;
/
