-- Synthetic bounded catalog case ORA-TYPE-058-CASE-02; Oracle 26ai.
DECLARE
 v_canonical VARCHAR2(128);
 v_null_value VARCHAR2(128);
 v_boundary VARCHAR2(128);
 v_recovery VARCHAR2(128);
 v_session_value VARCHAR2(128);
 v_sink VARCHAR2(128);
 v_zoned TIMESTAMP WITH TIME ZONE;
 v_length NUMBER; v_comparison NUMBER; v_overflow_code NUMBER := 0; v_json VARCHAR2(4000);
BEGIN
 SELECT TO_CHAR((EXTRACT(YEAR FROM INTERVAL '1-2' YEAR TO MONTH) * 12 + EXTRACT(MONTH FROM INTERVAL '1-2' YEAR TO MONTH)), 'FM9999999990'), TO_CHAR((EXTRACT(YEAR FROM CAST(NULL AS INTERVAL YEAR TO MONTH)) * 12 + EXTRACT(MONTH FROM CAST(NULL AS INTERVAL YEAR TO MONTH))), 'FM9999999990'), TO_CHAR((EXTRACT(YEAR FROM INTERVAL '100-1' YEAR(3) TO MONTH) * 12 + EXTRACT(MONTH FROM INTERVAL '100-1' YEAR(3) TO MONTH)), 'FM9999999990'), TO_CHAR((EXTRACT(YEAR FROM INTERVAL '-1-2' YEAR TO MONTH) * 12 + EXTRACT(MONTH FROM INTERVAL '-1-2' YEAR TO MONTH)), 'FM9999999990'), CASE WHEN INTERVAL '1-2' YEAR TO MONTH > INTERVAL '-1-2' YEAR TO MONTH THEN 1 ELSE 0 END INTO v_canonical, v_null_value, v_boundary, v_session_value, v_comparison FROM dual;
 BEGIN
 SELECT TO_CHAR(TO_YMINTERVAL('invalid')) INTO v_sink FROM dual;
 EXCEPTION WHEN OTHERS THEN v_overflow_code := SQLCODE;
 END;
 SELECT TO_CHAR((EXTRACT(YEAR FROM INTERVAL '1-2' YEAR TO MONTH) * 12 + EXTRACT(MONTH FROM INTERVAL '1-2' YEAR TO MONTH)), 'FM9999999990') INTO v_recovery FROM dual;
 SELECT JSON_OBJECT('case_id' VALUE 'ORA-TYPE-058-CASE-02', 'observations' VALUE
 JSON_OBJECT('boundary' VALUE v_boundary, 'null_value' VALUE v_null_value NULL ON NULL) RETURNING VARCHAR2(4000)) INTO v_json FROM dual;
 DBMS_OUTPUT.PUT_LINE('LY_TYPES_OBSERVATION=' || v_json);
END;
/
