-- Synthetic bounded catalog case ORA-TYPE-008-CASE-01; Oracle 26ai.
DECLARE
 v_canonical VARCHAR2(128);
 v_null_value VARCHAR2(128);
 v_boundary VARCHAR2(128);
 v_recovery VARCHAR2(128);
 v_session_value VARCHAR2(128);
 v_sink VARCHAR2(128);
 v_zoned TIMESTAMP WITH TIME ZONE;
 v_length NUMBER; v_comparison NUMBER; v_overflow_code NUMBER := 0; v_json VARCHAR2(4000);
BEGIN
 SELECT RAWTOHEX(UTL_RAW.CAST_FROM_BINARY_FLOAT(CAST(1.5 AS BINARY_FLOAT), UTL_RAW.BIG_ENDIAN)), RAWTOHEX(UTL_RAW.CAST_FROM_BINARY_FLOAT(CAST(NULL AS BINARY_FLOAT), UTL_RAW.BIG_ENDIAN)), RAWTOHEX(UTL_RAW.CAST_FROM_BINARY_FLOAT(CAST('1.1754943508222875e-38' AS BINARY_FLOAT), UTL_RAW.BIG_ENDIAN)), CASE WHEN CAST('-0' AS BINARY_FLOAT) = CAST('0' AS BINARY_FLOAT) THEN '1' ELSE '0' END, CASE WHEN BINARY_FLOAT_NAN = BINARY_FLOAT_NAN AND BINARY_FLOAT_NAN > BINARY_FLOAT_INFINITY THEN 1 ELSE 0 END INTO v_canonical, v_null_value, v_boundary, v_session_value, v_comparison FROM dual;
 BEGIN
 SELECT TO_BINARY_FLOAT('not-a-number') INTO v_sink FROM dual;
 EXCEPTION WHEN OTHERS THEN v_overflow_code := SQLCODE;
 END;
 SELECT RAWTOHEX(UTL_RAW.CAST_FROM_BINARY_FLOAT(CAST(1.5 AS BINARY_FLOAT), UTL_RAW.BIG_ENDIAN)) INTO v_recovery FROM dual;
 SELECT JSON_OBJECT('case_id' VALUE 'ORA-TYPE-008-CASE-01', 'observations' VALUE
 JSON_OBJECT('boundary' VALUE v_boundary NULL ON NULL) RETURNING VARCHAR2(4000)) INTO v_json FROM dual;
 DBMS_OUTPUT.PUT_LINE('LY_TYPES_OBSERVATION=' || v_json);
END;
/
