CREATE TABLE CARDDEMO.AUTHFRDS (
  AUTH_ID DECIMAL(11,0) NOT NULL,
  CARD_NUM CHAR(16) NOT NULL,
  AUTH_STATUS CHAR(1) NOT NULL,
  PRIMARY KEY (AUTH_ID)
);
CREATE UNIQUE INDEX CARDDEMO.AUTHFRDS_IX1
  ON CARDDEMO.AUTHFRDS (CARD_NUM, AUTH_ID);
