CREATE OR REPLACE PROCEDURE CARDDEMO.GET_AUTH_STATUS (
  P_CARD_NUM IN VARCHAR2,
  P_STATUS OUT VARCHAR2
) AS
BEGIN
  SELECT AUTH_FRAUD
    INTO P_STATUS
    FROM CARDDEMO.AUTHFRDS
   WHERE CARD_NUM = P_CARD_NUM;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    P_STATUS := 'N';
END;
/

CREATE OR REPLACE PROCEDURE CARDDEMO.SET_FRAUD_FLAG (
  P_CARD_NUM IN VARCHAR2,
  P_REASON IN VARCHAR2,
  P_ROWS OUT NUMBER
) AS
BEGIN
  UPDATE CARDDEMO.AUTHFRDS
     SET AUTH_FRAUD = 'Y',
         AUTH_RESP_REASON = P_REASON
   WHERE CARD_NUM = P_CARD_NUM;
  P_ROWS := SQL%ROWCOUNT;
END;
/

CREATE OR REPLACE PROCEDURE CARDDEMO.CLASSIFY_AMOUNT (
  P_AMOUNT IN NUMBER,
  P_CLASS OUT VARCHAR2
) AS
BEGIN
  IF P_AMOUNT < 0 THEN
    RAISE_APPLICATION_ERROR(-20001, 'NEGATIVE_AMOUNT');
  ELSIF P_AMOUNT >= 1000 THEN
    P_CLASS := 'HIGH';
  ELSE
    P_CLASS := 'STANDARD';
  END IF;
END;
/

CREATE OR REPLACE PROCEDURE CARDDEMO.NORMALIZE_REASON (
  P_REASON IN VARCHAR2,
  P_RESULT OUT VARCHAR2
) AS
BEGIN
  P_RESULT := NVL(P_REASON, 'UNSPECIFIED');
END;
/
