-- Authored public M0 trap; NOT natively qualified.
CREATE SCHEMA IF NOT EXISTS dbo;
CREATE TABLE dbo.effects(id integer PRIMARY KEY, amount integer NOT NULL);
CREATE TABLE dbo.items(id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,v integer);
