BEGIN EXECUTE IMMEDIATE 'DROP USER CARDDEMO CASCADE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/

CREATE USER CARDDEMO NO AUTHENTICATION;

DECLARE
  FD_DEFAULT_TABLESPACE VARCHAR2(128);
BEGIN
  SELECT PROPERTY_VALUE INTO FD_DEFAULT_TABLESPACE
  FROM DATABASE_PROPERTIES
  WHERE PROPERTY_NAME='DEFAULT_PERMANENT_TABLESPACE';
  EXECUTE IMMEDIATE 'ALTER USER CARDDEMO QUOTA UNLIMITED ON ' ||
    DBMS_ASSERT.ENQUOTE_NAME(FD_DEFAULT_TABLESPACE, FALSE);
END;
/

CREATE TABLE CARDDEMO.AUTHFRDS (
  CARD_NUM CHAR(16 CHAR) NOT NULL,
  AUTH_TS TIMESTAMP(6) NOT NULL,
  AUTH_TYPE CHAR(4 CHAR),
  CARD_EXPIRY_DATE CHAR(4 CHAR),
  MESSAGE_TYPE CHAR(6 CHAR),
  MESSAGE_SOURCE CHAR(6 CHAR),
  AUTH_ID_CODE CHAR(6 CHAR),
  AUTH_RESP_CODE CHAR(2 CHAR),
  AUTH_RESP_REASON CHAR(4 CHAR),
  PROCESSING_CODE CHAR(6 CHAR),
  TRANSACTION_AMT NUMBER(12,2),
  APPROVED_AMT NUMBER(12,2),
  MERCHANT_CATAGORY_CODE CHAR(4 CHAR),
  ACQR_COUNTRY_CODE CHAR(3 CHAR),
  POS_ENTRY_MODE NUMBER(5,0),
  MERCHANT_ID CHAR(15 CHAR),
  MERCHANT_NAME VARCHAR2(22 CHAR),
  MERCHANT_CITY CHAR(13 CHAR),
  MERCHANT_STATE CHAR(2 CHAR),
  MERCHANT_ZIP CHAR(9 CHAR),
  TRANSACTION_ID CHAR(15 CHAR),
  MATCH_STATUS CHAR(1 CHAR),
  AUTH_FRAUD CHAR(1 CHAR),
  FRAUD_RPT_DATE DATE,
  ACCT_ID NUMBER(11,0),
  CUST_ID NUMBER(9,0),
  CONSTRAINT PK_AUTHFRDS PRIMARY KEY (CARD_NUM, AUTH_TS)
);

CREATE UNIQUE INDEX CARDDEMO.XAUTHFRD ON CARDDEMO.AUTHFRDS (CARD_NUM ASC, AUTH_TS DESC);
