-- Authored public M0 trap; NOT natively qualified.
CREATE SCHEMA IF NOT EXISTS dbo;
CREATE TABLE dbo.effects(id integer PRIMARY KEY, amount integer NOT NULL);
CREATE TABLE dbo.items(id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,v integer);
CREATE TABLE dbo.audit(id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 100) PRIMARY KEY,v integer);
CREATE FUNCTION dbo.items_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN INSERT INTO dbo.audit(v) VALUES(NEW.v); RETURN NEW; END; $$;
CREATE TRIGGER items_audit AFTER INSERT ON dbo.items FOR EACH ROW EXECUTE FUNCTION dbo.items_audit();
