spring.application.name=carddemo-spring-batch-candidate
spring.main.web-application-type=none
spring.batch.jdbc.initialize-schema=always
spring.batch.job.name=cardDemoIntcalcJob
logging.level.root=INFO

carddemo.processing-date=2022071800
carddemo.timestamp=2022-07-18-00.00.00.000000
carddemo.final-account-policy=source-faithful

