-- liquibase formatted sql

--changeset account:postgresql-transaction-core-1
DROP TABLE IF EXISTS transfer_commands CASCADE;
DROP TABLE IF EXISTS journal CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;

CREATE TABLE accounts (
    account_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name varchar(40) NOT NULL,
    account_type varchar(2) CHECK (account_type IN ('CH', 'SA', 'CC', 'LO')),
    customer_id varchar(20),
    account_opened_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    account_other_details varchar(256),
    account_balance bigint NOT NULL
);

CREATE TABLE journal (
    journal_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_type varchar(20) NOT NULL,
    lra_id varchar(1024),
    lra_state varchar(40),
    journal_amount bigint NOT NULL,
    account_id bigint NOT NULL REFERENCES accounts(account_id)
);

CREATE TABLE transfer_commands (
    command_id varchar(96) PRIMARY KEY,
    source_account_id bigint NOT NULL REFERENCES accounts(account_id),
    target_account_id bigint NOT NULL REFERENCES accounts(account_id),
    amount bigint NOT NULL CHECK (amount > 0),
    state varchar(24) NOT NULL,
    actor varchar(80) NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT transfer_distinct_accounts CHECK (source_account_id <> target_account_id)
);

CREATE UNIQUE INDEX journal_command_kind_uq ON journal(lra_id, journal_type);

--rollback DROP TABLE transfer_commands;
--rollback DROP TABLE journal;
--rollback DROP TABLE accounts;
